/* tslint:disable */
/* eslint-disable */
/**
 * Teknoy EMS API
 * API for Teknoy EMS
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UserDTO } from './user-dto';

/**
 *
 * @export
 * @interface ActivityLogDTO
 */
export interface ActivityLogDTO {
  /**
   *
   * @type {string}
   * @memberof ActivityLogDTO
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof ActivityLogDTO
   */
  userId: string;
  /**
   *
   * @type {UserDTO}
   * @memberof ActivityLogDTO
   */
  user: UserDTO;
  /**
   *
   * @type {string}
   * @memberof ActivityLogDTO
   */
  action: ActivityLogDTOActionEnum;
  /**
   *
   * @type {string}
   * @memberof ActivityLogDTO
   */
  entityName: string;
  /**
   *
   * @type {string}
   * @memberof ActivityLogDTO
   */
  entityId: string;
  /**
   *
   * @type {string}
   * @memberof ActivityLogDTO
   */
  oldValue?: string;
  /**
   *
   * @type {string}
   * @memberof ActivityLogDTO
   */
  newValue?: string;
  /**
   *
   * @type {string}
   * @memberof ActivityLogDTO
   */
  executedAt: string;
  /**
   *
   * @type {string}
   * @memberof ActivityLogDTO
   */
  createdAt: string;
  /**
   *
   * @type {string}
   * @memberof ActivityLogDTO
   */
  updatedAt?: string;
  /**
   *
   * @type {string}
   * @memberof ActivityLogDTO
   */
  priority: ActivityLogDTOPriorityEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum ActivityLogDTOActionEnum {
  Added = 'ADDED',
  Edited = 'EDITED',
  Deleted = 'DELETED',
  Reserved = 'RESERVED',
  Registered = 'REGISTERED',
}
/**
 * @export
 * @enum {string}
 */
export enum ActivityLogDTOPriorityEnum {
  Public = 'PUBLIC',
  Private = 'PRIVATE',
  Important = 'IMPORTANT',
}
