/* tslint:disable */
/* eslint-disable */
/**
 * Teknoy EMS API
 * API for Teknoy EMS
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AnnouncementReportFilterDTO
 */
export interface AnnouncementReportFilterDTO {
  /**
   *
   * @type {boolean}
   * @memberof AnnouncementReportFilterDTO
   */
  id?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof AnnouncementReportFilterDTO
   */
  title?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof AnnouncementReportFilterDTO
   */
  subtitle?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof AnnouncementReportFilterDTO
   */
  content?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof AnnouncementReportFilterDTO
   */
  tags?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof AnnouncementReportFilterDTO
   */
  viewAccess?: boolean;
}
