/* tslint:disable */
/* eslint-disable */
/**
 * Teknoy EMS API
 * API for Teknoy EMS
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface EquipmentReportFilterDTO
 */
export interface EquipmentReportFilterDTO {
  /**
   *
   * @type {boolean}
   * @memberof EquipmentReportFilterDTO
   */
  type?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof EquipmentReportFilterDTO
   */
  brand?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof EquipmentReportFilterDTO
   */
  serial?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof EquipmentReportFilterDTO
   */
  schedules?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof EquipmentReportFilterDTO
   */
  notes?: boolean;
}
