/* tslint:disable */
/* eslint-disable */
/**
 * Teknoy EMS API
 * API for Teknoy EMS
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ErrorFieldDTO
 */
export interface ErrorFieldDTO {
  /**
   *
   * @type {string}
   * @memberof ErrorFieldDTO
   */
  fieldName: string;
  /**
   *
   * @type {string}
   * @memberof ErrorFieldDTO
   */
  errorMessage: string;
}
