/* tslint:disable */
/* eslint-disable */
/**
 * Teknoy EMS API
 * API for Teknoy EMS
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EquipmentDTO } from './equipment-dto';
import { OrganizerDTO } from './organizer-dto';
import { UserDTO } from './user-dto';
import { VenueDTO } from './venue-dto';

/**
 *
 * @export
 * @interface EventDTO
 */
export interface EventDTO {
  /**
   *
   * @type {string}
   * @memberof EventDTO
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof EventDTO
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof EventDTO
   */
  description: string;
  /**
   *
   * @type {string}
   * @memberof EventDTO
   */
  status: EventDTOStatusEnum;
  /**
   *
   * @type {string}
   * @memberof EventDTO
   */
  startTime: string;
  /**
   *
   * @type {string}
   * @memberof EventDTO
   */
  endTime: string;
  /**
   *
   * @type {string}
   * @memberof EventDTO
   */
  contactPerson: string;
  /**
   *
   * @type {string}
   * @memberof EventDTO
   */
  contactNumber: string;
  /**
   *
   * @type {string}
   * @memberof EventDTO
   */
  approvedBy: string;
  /**
   *
   * @type {string}
   * @memberof EventDTO
   */
  viewAccess: EventDTOViewAccessEnum;
  /**
   *
   * @type {string}
   * @memberof EventDTO
   */
  type: EventDTOTypeEnum;
  /**
   *
   * @type {string}
   * @memberof EventDTO
   */
  additionalNotes?: string;
  /**
   *
   * @type {OrganizerDTO}
   * @memberof EventDTO
   */
  organizer: OrganizerDTO;
  /**
   *
   * @type {UserDTO}
   * @memberof EventDTO
   */
  encodedBy: UserDTO;
  /**
   *
   * @type {Array<EquipmentDTO>}
   * @memberof EventDTO
   */
  equipments: Array<EquipmentDTO>;
  /**
   *
   * @type {Array<VenueDTO>}
   * @memberof EventDTO
   */
  venues: Array<VenueDTO>;
}

/**
 * @export
 * @enum {string}
 */
export enum EventDTOStatusEnum {
  Pending = 'PENDING',
  Ongoing = 'ONGOING',
  Reserved = 'RESERVED',
  Done = 'DONE',
  Canceled = 'CANCELED',
  Postponed = 'POSTPONED',
}
/**
 * @export
 * @enum {string}
 */
export enum EventDTOViewAccessEnum {
  Public = 'PUBLIC',
  Private = 'PRIVATE',
}
/**
 * @export
 * @enum {string}
 */
export enum EventDTOTypeEnum {
  Corporate = 'CORPORATE',
  Academic = 'ACADEMIC',
  Seminar = 'SEMINAR',
  Conference = 'CONFERENCE',
  CampusWide = 'CAMPUS_WIDE',
  Virtual = 'VIRTUAL',
  Sports = 'SPORTS',
  Others = 'OTHERS',
}
