/* tslint:disable */
/* eslint-disable */
/**
 * Teknoy EMS API
 * API for Teknoy EMS
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface EventCreateDTO
 */
export interface EventCreateDTO {
  /**
   *
   * @type {string}
   * @memberof EventCreateDTO
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof EventCreateDTO
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof EventCreateDTO
   */
  description?: string;
  /**
   *
   * @type {string}
   * @memberof EventCreateDTO
   */
  status: EventCreateDTOStatusEnum;
  /**
   *
   * @type {string}
   * @memberof EventCreateDTO
   */
  startTime: string;
  /**
   *
   * @type {string}
   * @memberof EventCreateDTO
   */
  endTime: string;
  /**
   *
   * @type {string}
   * @memberof EventCreateDTO
   */
  contactPerson: string;
  /**
   *
   * @type {string}
   * @memberof EventCreateDTO
   */
  contact: string;
  /**
   *
   * @type {string}
   * @memberof EventCreateDTO
   */
  approvedBy?: string;
  /**
   *
   * @type {string}
   * @memberof EventCreateDTO
   */
  viewAccess: EventCreateDTOViewAccessEnum;
  /**
   *
   * @type {string}
   * @memberof EventCreateDTO
   */
  type: EventCreateDTOTypeEnum;
  /**
   *
   * @type {string}
   * @memberof EventCreateDTO
   */
  additionalNotes?: string;
  /**
   *
   * @type {string}
   * @memberof EventCreateDTO
   */
  organizerId?: string;
  /**
   *
   * @type {string}
   * @memberof EventCreateDTO
   */
  encodedById?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof EventCreateDTO
   */
  equipmentIds: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof EventCreateDTO
   */
  venueIds: Array<string>;
}

/**
 * @export
 * @enum {string}
 */
export enum EventCreateDTOStatusEnum {
  Pending = 'PENDING',
  Ongoing = 'ONGOING',
  Reserved = 'RESERVED',
  Done = 'DONE',
  Canceled = 'CANCELED',
  Postponed = 'POSTPONED',
}
/**
 * @export
 * @enum {string}
 */
export enum EventCreateDTOViewAccessEnum {
  Public = 'PUBLIC',
  Private = 'PRIVATE',
}
/**
 * @export
 * @enum {string}
 */
export enum EventCreateDTOTypeEnum {
  PhotoDocumentation = 'PHOTO_DOCUMENTATION',
  VideoDocumentation = 'VIDEO_DOCUMENTATION',
  PhotoAndVideoDocumentation = 'PHOTO_AND_VIDEO_DOCUMENTATION',
  LiveStreaming = 'LIVE_STREAMING',
  MusicBand = 'MUSIC_BAND',
  Others = 'OTHERS',
}
