/* tslint:disable */
/* eslint-disable */
/**
 * Teknoy EMS API
 * API for Teknoy EMS
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface EventReportFilterDTO
 */
export interface EventReportFilterDTO {
  /**
   *
   * @type {boolean}
   * @memberof EventReportFilterDTO
   */
  id?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof EventReportFilterDTO
   */
  title?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof EventReportFilterDTO
   */
  description?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof EventReportFilterDTO
   */
  status?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof EventReportFilterDTO
   */
  startTime?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof EventReportFilterDTO
   */
  endTime?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof EventReportFilterDTO
   */
  contactPerson?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof EventReportFilterDTO
   */
  contact?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof EventReportFilterDTO
   */
  approvedBy?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof EventReportFilterDTO
   */
  viewAccess?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof EventReportFilterDTO
   */
  type?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof EventReportFilterDTO
   */
  additionalNotes?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof EventReportFilterDTO
   */
  organizer?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof EventReportFilterDTO
   */
  encodedBy?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof EventReportFilterDTO
   */
  equipments?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof EventReportFilterDTO
   */
  venues?: boolean;
}
