/* tslint:disable */
/* eslint-disable */
/**
 * Teknoy EMS API
 * API for Teknoy EMS
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetSortedDTO
 */
export interface GetSortedDTO {
  /**
   *
   * @type {string}
   * @memberof GetSortedDTO
   */
  startTime: string;
  /**
   *
   * @type {string}
   * @memberof GetSortedDTO
   */
  endTime: string;
}
