/* tslint:disable */
/* eslint-disable */
/**
 * Teknoy EMS API
 * API for Teknoy EMS
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ActivityLogDTO } from './activity-log-dto';

/**
 *
 * @export
 * @interface NotificationDTO
 */
export interface NotificationDTO {
  /**
   *
   * @type {string}
   * @memberof NotificationDTO
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof NotificationDTO
   */
  userId: string;
  /**
   *
   * @type {string}
   * @memberof NotificationDTO
   */
  activityLogId: string;
  /**
   *
   * @type {ActivityLogDTO}
   * @memberof NotificationDTO
   */
  activityLog: ActivityLogDTO;
  /**
   *
   * @type {string}
   * @memberof NotificationDTO
   */
  createdAt?: string;
  /**
   *
   * @type {string}
   * @memberof NotificationDTO
   */
  updatedAt?: string;
  /**
   *
   * @type {boolean}
   * @memberof NotificationDTO
   */
  unread: boolean;
}
