/* tslint:disable */
/* eslint-disable */
/**
 * Teknoy EMS API
 * API for Teknoy EMS
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface OrganizerDTO
 */
export interface OrganizerDTO {
  /**
   *
   * @type {string}
   * @memberof OrganizerDTO
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof OrganizerDTO
   */
  createdAt?: string;
  /**
   *
   * @type {string}
   * @memberof OrganizerDTO
   */
  updatedAt?: string;
  /**
   *
   * @type {string}
   * @memberof OrganizerDTO
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof OrganizerDTO
   */
  type: OrganizerDTOTypeEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum OrganizerDTOTypeEnum {
  Department = 'DEPARTMENT',
  Organization = 'ORGANIZATION',
  Others = 'OTHERS',
}
