/* tslint:disable */
/* eslint-disable */
/**
 * Teknoy EMS API
 * API for Teknoy EMS
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ReportFilterDTO } from './report-filter-dto';

/**
 *
 * @export
 * @interface ReportGetDTO
 */
export interface ReportGetDTO {
  /**
   *
   * @type {string}
   * @memberof ReportGetDTO
   */
  message?: string;
  /**
   *
   * @type {ReportFilterDTO}
   * @memberof ReportGetDTO
   */
  reportFilterDTO: ReportFilterDTO;
}
