/* tslint:disable */
/* eslint-disable */
/**
 * Teknoy EMS API
 * API for Teknoy EMS
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AnnouncementReportFilterDTO } from './announcement-report-filter-dto';
import { EquipmentReportFilterDTO } from './equipment-report-filter-dto';
import { EventReportFilterDTO } from './event-report-filter-dto';
import { OrganizerReportFilterDTO } from './organizer-report-filter-dto';
import { VenueReportFilterDTO } from './venue-report-filter-dto';

/**
 *
 * @export
 * @interface ReportFilterDTO
 */
export interface ReportFilterDTO {
  /**
   *
   * @type {EventReportFilterDTO}
   * @memberof ReportFilterDTO
   */
  eventReportFilterDTO: EventReportFilterDTO;
  /**
   *
   * @type {AnnouncementReportFilterDTO}
   * @memberof ReportFilterDTO
   */
  announcementReportFilterDTO: AnnouncementReportFilterDTO;
  /**
   *
   * @type {EquipmentReportFilterDTO}
   * @memberof ReportFilterDTO
   */
  equipmentReportFilterDTO: EquipmentReportFilterDTO;
  /**
   *
   * @type {OrganizerReportFilterDTO}
   * @memberof ReportFilterDTO
   */
  organizerReportFilterDTO: OrganizerReportFilterDTO;
  /**
   *
   * @type {VenueReportFilterDTO}
   * @memberof ReportFilterDTO
   */
  venueReportFilterDTO: VenueReportFilterDTO;
}
