/* tslint:disable */
/* eslint-disable */
/**
 * Teknoy EMS API
 * API for Teknoy EMS
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ScheduleDTO
 */
export interface ScheduleDTO {
  /**
   *
   * @type {string}
   * @memberof ScheduleDTO
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof ScheduleDTO
   */
  availability: ScheduleDTOAvailabilityEnum;
  /**
   *
   * @type {string}
   * @memberof ScheduleDTO
   */
  startTime: string;
  /**
   *
   * @type {string}
   * @memberof ScheduleDTO
   */
  endTime: string;
}

/**
 * @export
 * @enum {string}
 */
export enum ScheduleDTOAvailabilityEnum {
  Available = 'AVAILABLE',
  Unavailable = 'UNAVAILABLE',
}
