/* tslint:disable */
/* eslint-disable */
/**
 * Teknoy EMS API
 * API for Teknoy EMS
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EquipmentDTO } from './equipment-dto';

/**
 *
 * @export
 * @interface SortedEquipmentsDTO
 */
export interface SortedEquipmentsDTO {
  /**
   *
   * @type {Array<EquipmentDTO>}
   * @memberof SortedEquipmentsDTO
   */
  availableEquipments: Array<EquipmentDTO>;
  /**
   *
   * @type {Array<EquipmentDTO>}
   * @memberof SortedEquipmentsDTO
   */
  unavailableEquipments: Array<EquipmentDTO>;
}
