/* tslint:disable */
/* eslint-disable */
/**
 * Teknoy EMS API
 * API for Teknoy EMS
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface VenueReportFilterDTO
 */
export interface VenueReportFilterDTO {
  /**
   *
   * @type {boolean}
   * @memberof VenueReportFilterDTO
   */
  id?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof VenueReportFilterDTO
   */
  name?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof VenueReportFilterDTO
   */
  notes?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof VenueReportFilterDTO
   */
  schedule?: boolean;
}
