export enum WebSocketEnum {
  NOTIFICATION = 'NOTIFICATION',
  NOTIFICATIONS_ACTIVITY = 'NOTIFICATIONS_ACTIVITY',
  UPDATE_EQUIPMENTS_TABLE = 'UPDATE_EQUIPMENTS_TABLE',
  UPDATE_ANNOUNCEMENTS_TABLE = 'UPDATE_ANNOUNCEMENTS_TABLE',
  UPDATE_ACCOUNTS_TABLE = 'UPDATE_ACCOUNTS_TABLE',
  UPDATE_EVENTS_TABLE = 'UPDATE_EVENTS_TABLE',
  UPDATE_ORGANIZERS_TABLE = 'UPDATE_ORGANIZERS_TABLE',
  UPDATE_VENUES_TABLE = 'UPDATE_VENUES_TABLE',
  UPDATE_TABLES = 'UPDATE_TABLES',
}
